version: 2.1

orbs:
  node: circleci/node@5.1.0
  python: circleci/python@2.1.1

jobs:
  test-apps:
    docker:
      - image: cimg/python:3.12.0-node
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: backend/requirements.txt
      - run:
          name: Test Authentication App
          command: python backend/manage.py test authentication
      - run:
          name: Test Mail Serv App
          command: python backend/manage.py test mail_serv
      - run:
          name: Test Event Management App
          command: python backend/manage.py test event_management
      - node/install-packages:
          pkg-manager: npm
          app-dir: frontend
      - run:
          name: Test Frontend
          command: cd frontend && npm test

workflows:
  app-workflow:
    jobs:
      - test-apps
